{"uuid": "55cfa440-99a6-4c8f-b8f9-5a0affeb8ebc", "children": ["28595924-c897-4789-97df-5d55065fb263"], "befores": [{"name": "_xunit_setup_method_fixture_TestEmail", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=126.0.6478.183)\nStacktrace:\n\tGetHandleVerifier [0x00007FF7E795EEB2+31554]\n\t(No symbol) [0x00007FF7E78D7EE9]\n\t(No symbol) [0x00007FF7E779872A]\n\t(No symbol) [0x00007FF7E776D995]\n\t(No symbol) [0x00007FF7E78144D7]\n\t(No symbol) [0x00007FF7E782C051]\n\t(No symbol) [0x00007FF7E780CDD3]\n\t(No symbol) [0x00007FF7E77DA33B]\n\t(No symbol) [0x00007FF7E77DAED1]\n\tGetHandleVerifier [0x00007FF7E7C68B2D+3217341]\n\tGetHandleVerifier [0x00007FF7E7CB5AF3+3532675]\n\tGetHandleVerifier [0x00007FF7E7CAB0F0+3489152]\n\tGetHandleVerifier [0x00007FF7E7A0E786+750614]\n\t(No symbol) [0x00007FF7E78E376F]\n\t(No symbol) [0x00007FF7E78DEB24]\n\t(No symbol) [0x00007FF7E78DECB2]\n\t(No symbol) [0x00007FF7E78CE17F]\n\tBaseThreadInitThunk [0x00007FFABA49257D+29]\n\tRtlUserThreadStart [0x00007FFABA84AF28+40]\n\n", "trace": "  File \"C:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"C:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 1125, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 880, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\python.py\", line 820, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"C:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\_pytest\\python.py\", line 716, in _call_with_optional_argument\n    func()\n  File \"C:\\Users\\hp\\Desktop\\a工作相关\\163邮箱\\testcase\\test_send_email.py\", line 21, in setup_method\n    self.login_page.switch_to_frame_login()\n  File \"C:\\Users\\hp\\Desktop\\a工作相关\\163邮箱\\pageobjects\\login_page.py\", line 24, in switch_to_frame_login\n    el_frame = self.find_element(*self.login_iframe)\n  File \"C:\\Users\\hp\\Desktop\\a工作相关\\163邮箱\\common\\BaseView.py\", line 19, in find_element\n    element = wait.until(lambda x: x.find_element(*loc))\n  File \"C:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 96, in until\n    value = method(self._driver)\n  File \"C:\\Users\\hp\\Desktop\\a工作相关\\163邮箱\\common\\BaseView.py\", line 19, in <lambda>\n    element = wait.until(lambda x: x.find_element(*loc))\n  File \"C:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 748, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n  File \"C:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1721894969543, "stop": 1721894974089}], "start": 1721894969543, "stop": 1721894974114}